sourcePath=/tmp/miriam/12_graph_copy
pathMap=/data/bulktagging/pathMap
baseURL=https://services.openaire.eu/openaire/community/
taggingCriteria={"tags":[{"id":"SM","criteria":[{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"supplementary material for"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"supplementary document for"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"figure"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"supplementary figure"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"supplemental figure"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"supplementary table"}]},{"constraint":[{"verb":"starts_with_caseinsensitive","field":"title","value":"table for"}]}]}]}
#pathMap
#{
#"author":{
#"path":"$['author'][*]['fullname']"
#},
#"title":{
#"path":"$['title'][*]['value']"
#},
#"orcid":{
#"path":"$['author'][*]['pid'][*][?(@['qualifier']['classid']=='orcid')]['value']"
#},
#"orcid_pending":{
#"path":"$['author'][*]['pid'][*][?(@['qualifier']['classid']=='orcid_pending')]['value']"
#},
#"contributor":{
#"path":"$['contributor'][*]['value']"
#},
#"description":{
#"path":"$['description'][*]['value']"
#},
#"subject":{
#"path":"$['subject'][*]['value']"
#},
#"fos":{
#"path":"$['subject'][?(@['qualifier']['classid']=='FOS')].value"
#},
#"sdg":{
#"path":"$['subject'][?(@['qualifier']['classid']=='SDG')].value"
#},
#"journal":{
#"path":"$['journal'].name"
#},
#"hostedby":{
#"path":"$['instance'][*]['hostedby']['key']"
#},
#"collectedfrom":{
#"path":"$['instance'][*]['collectedfrom']['key']"
#},
#"publisher":{
#"path":"$['publisher'].value"
#},
#"access":{
#"path":"$['bestaccessright'].classid"
#},
#"documentType":{
#"path":"$['instance'][*]['instancetype'].classname"
#},
#"language":{
#"path":"$['language'].classid"
#},
#"resultType":{
#"path":"$['resulttype'].classid"
#},
#"pids":"$['pid'][*]",
#"publicationyear":{
#"path":"$['dateofacceptance'].value",
#"action":{
#"clazz":"eu.dnetlib.dhp.bulktag.actions.ExecSubstringAction",
#"method":"execSubstring",
#"params":[
#{
#"paramName":"From",
#"paramValue":0
#},
#{
#"paramName":"To",
#"paramValue":4
#}
#]
#}
#}
#}