package eu.dnetlib.pace.model

import eu.dnetlib.pace.config.{DedupConfig, Type}
import eu.dnetlib.pace.util.{BlockProcessor, SparkReporter}
import org.apache.spark.SparkContext
import org.apache.spark.sql.catalyst.expressions.Literal
import org.apache.spark.sql.expressions._
import org.apache.spark.sql.functions.{col, desc, expr, lit, udf}
import org.apache.spark.sql.types._
import org.apache.spark.sql.{Column, Dataset, Row, SaveMode, functions}

import java.util.stream.Collectors
import scala.collection.JavaConverters._

case class SparkDeduper(conf: DedupConfig) extends Serializable {

  val model: SparkModel = SparkModel(conf)

  val dedup: (Dataset[Row] => Dataset[Row]) = df => {
    df.transform(generateClustersWithCollect)
      .transform(processBlocks)
  }

  val generateClustersWithCollect: (Dataset[Row] => Dataset[Row]) = df_with_filters => {
    var df_with_clustering_keys: Dataset[Row] = null

    for ((cd, idx) <- conf.clusterings().asScala.zipWithIndex) {
      val inputColumns = cd.getFields.asScala.foldLeft(Seq[Column]())((acc, fName) => {
        val column = if (conf.blacklists.containsKey(fName))
          Seq(col(fName + "_filtered"))
        else
          Seq(col(fName))

        acc ++ column
      })

      // Add 'key' column with the value generated by the given clustering definition
      val ds: Dataset[Row] = df_with_filters
        .withColumn("clustering", lit(cd.getName + "::" + idx))
        .withColumn("key", functions.explode(clusterValuesUDF(cd).apply(functions.array(inputColumns: _*))))
        // Add position column having the position of the row within the set of rows having the same key value ordered by the sorting value
        .withColumn("position", functions.row_number().over(Window.partitionBy("key").orderBy(col(model.orderingFieldName), col(model.identifierFieldName))))
       // .withColumn("count", functions.max("position").over(Window.partitionBy("key").orderBy(col(model.orderingFieldName), col(model.identifierFieldName)).rowsBetween(Window.unboundedPreceding,Window.unboundedFollowing) ))
       // .filter("count > 1")

      if (df_with_clustering_keys == null)
        df_with_clustering_keys = ds
      else
        df_with_clustering_keys = df_with_clustering_keys.union(ds)
    }

    //TODO: analytics
    /*df_with_clustering_keys.groupBy(col("clustering"), col("key"))
      .agg(expr("max(count) AS size"))
      .orderBy(desc("size"))
      .show*/

    val df_with_blocks = df_with_clustering_keys
      // split the clustering block into smaller blocks of queuemaxsize
      .groupBy(col("clustering"), col("key"), functions.floor(col("position").divide(lit(conf.getWf.getQueueMaxSize))))
      .agg(functions.collect_set(functions.struct(model.schema.fieldNames.map(col): _*)).as("block"))
      .filter(functions.size(new Column("block")).gt(1))
       .union(
        //adjacency blocks
        df_with_clustering_keys
          // filter out leading and trailing elements
          .filter(col("position").gt(conf.getWf.getSlidingWindowSize/2))
          //.filter(col("position").lt(col("count").minus(conf.getWf.getSlidingWindowSize/2)))
          // create small blocks of records on "the border" of maxqueuesize: getSlidingWindowSize/2 elements before and after
          .filter(
            col("position").mod(conf.getWf.getQueueMaxSize).lt(conf.getWf.getSlidingWindowSize/2) // slice of the start of block
            || col("position").mod(conf.getWf.getQueueMaxSize).gt(conf.getWf.getQueueMaxSize - (conf.getWf.getSlidingWindowSize/2)) //slice of the end of the block
          )
          .groupBy(col("clustering"), col("key"), functions.floor((col("position") + lit(conf.getWf.getSlidingWindowSize/2)).divide(lit(conf.getWf.getQueueMaxSize))))
          .agg(functions.collect_set(functions.struct(model.schema.fieldNames.map(col): _*)).as("block"))
          .filter(functions.size(new Column("block")).gt(1))
      )

    df_with_blocks
  }

  def clusterValuesUDF(cd: ClusteringDef) = {
    udf[Seq[String], Seq[Any]](values => {
      val valueList = values.flatMap {
        case a: Seq[_] => a.map(_.toString)
        case s: Any => Some(s.toString)
        case _ => None
      }

      cd.clusteringFunction().apply(conf, valueList.asJava).asScala.toSeq
    })
  }


  val processBlocks: (Dataset[Row] => Dataset[Row]) = df => {
    df.filter(functions.size(new Column("block")).geq(new Literal(2, DataTypes.IntegerType)))
      .withColumn("relations", processBlock(df.sparkSession.sparkContext).apply(new Column("block")))
      .select(functions.explode(new Column("relations")).as("relation"))
  }

  case class SimRelation(from: String, to: String)

  def processBlock(implicit sc: SparkContext) = {
    val accumulators = SparkReporter.constructAccumulator(conf, sc)

    udf[Seq[SimRelation], Seq[Any]](block => {
      val reporter = new SparkReporter(accumulators)

      val mapDocuments = block.asInstanceOf[Seq[Row]].asJava.stream()
        .sorted(new RowDataOrderingComparator(model.orderingFieldPosition, model.identityFieldPosition))
        .limit(conf.getWf.getQueueMaxSize)
        .collect(Collectors.toList[Row]())

      new BlockProcessor(conf, model.identityFieldPosition, model.orderingFieldPosition).processSortedRows(mapDocuments, reporter)


      reporter.getRelations.asScala.map(r => SimRelation(r._1, r._2)).toSeq
    }).asNondeterministic()
  }

}
